### ISSUE TITLE
pom.xml:217: bump up INSTRUCTION coverage branch coverage...

### ISSUE THREAD

**Issue by 0pdd** [h1alexbel/typehead-server#25]
The puzzle `3-ba2009c8` from #3 has to be resolved: 

https://github.com/h1alexbel/typehead-server/blob/c1618bc2956ec81f41df49c8ea6e1a7bc4220ffa/pom.xml#L217-L217

The puzzle was created by @h1alexbel on 24-Jul-23. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
I can't create github labels `pdd`. Most likely I don't have necessary permissions to `h1alexbel/typehead-server` repository. Please, make sure @0pdd user is in the [list of collaborators](https://github.com/h1alexbel/typehead-server/settings/collaboration):

```Octokit::NotFound
POST https://api.github.com/repos/h1alexbel/typehead-server/labels: 404 - Not Found // See: https://docs.github.com/rest/issues/labels#create-a-label
/app/vendor/bundle/ruby/2.7.0/gems/octokit-6.1.1/lib/octokit/response/raise_error.rb:14:in `on_complete'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.7.8/lib/faraday/middleware.rb:18:in `block in call'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.7.8/lib/faraday/response.rb:42:in `on_complete'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.7.8/lib/faraday/middleware.rb:17:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/octokit-6.1.1/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
/app/vendor/bundle/ruby/2.7.0/gems/octokit-6.1.1/lib/octokit/middleware/follow_redirects.rb:61:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.7.8/lib/faraday/rack_builder.rb:153:in `build_response'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.7.8/lib/faraday/connection.rb:444:in `run_request'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.7.8/lib/faraday/connection.rb:280:in `post'
/app/vendor/bundle/ruby/2.7.0/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/octokit-6.1.1/lib/octokit/connection.rb:156:in `request'
/app/vendor/bundle/ruby/2.7.0/gems/octokit-6.1.1/lib/octokit/connection.rb:28:in `post'
/app/vendor/bundle/ruby/2.7.0/gems/octokit-6.1.1/lib/octokit/client/labels.rb:44:in `add_label'
/app/objects/vcs/github.rb:92:in `add_label'
/app/objects/tickets/tagged_tickets.rb:45:in `block in submit'
/app/objects/tickets/tagged_tickets.rb:45:in `each'
/app/objects/tickets/tagged_tickets.rb:45:in `submit'
/app/objects/tickets/commit_tickets.rb:36:in `submit'
/app/objects/tickets/emailed_tickets.rb:35:in `submit'
/app/objects/tickets/sentry_tickets.rb:45:in `submit'
/app/objects/puzzles.rb:109:in `block in expose'
/app/objects/puzzles.rb:97:in `loop'
/app/objects/puzzles.rb:97:in `expose'
/app/objects/puzzles.rb:44:in `deploy'
/app/objects/jobs/job.rb:38:in `proceed'
/app/objects/jobs/job_starred.rb:32:in `proceed'
/app/objects/jobs/job_recorded.rb:31:in `proceed'
/app/objects/jobs/job_emailed.rb:33:in `proceed'
/app/objects/jobs/job_commiterrors.rb:33:in `proceed'
/app/objects/jobs/job_detached.rb:48:in `exclusive'
/app/objects/jobs/job_detached.rb:36:in `block in proceed'
/app/objects/jobs/job_detached.rb:36:in `fork'
/app/objects/jobs/job_detached.rb:36:in `proceed'
/app/0pdd.rb:531:in `process_request'
/app/0pdd.rb:367:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1706:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1706:in `block in compile!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1019:in `block (3 levels) in route!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1037:in `route_eval'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1019:in `block (2 levels) in route!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1068:in `block in process_route'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1066:in `catch'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1066:in `process_route'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1017:in `block in route!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1014:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1014:in `route!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1138:in `block in dispatch!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `catch'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `invoke'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1133:in `dispatch!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:949:in `block in call!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `catch'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `invoke'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:949:in `call!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:938:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.7/lib/rack/deflater.rb:44:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-3.0.6/lib/rack/protection/xss_header.rb:20:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-3.0.6/lib/rack/protection/path_traversal.rb:18:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-3.0.6/lib/rack/protection/json_csrf.rb:28:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-3.0.6/lib/rack/protection/base.rb:53:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-3.0.6/lib/rack/protection/base.rb:53:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-3.0.6/lib/rack/protection/frame_options.rb:33:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.7/lib/rack/logger.rb:17:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.7/lib/rack/common_logger.rb:38:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:261:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:254:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.7/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.7/lib/rack/method_override.rb:24:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:219:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:2018:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1576:in `block in call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1792:in `synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1576:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.7/lib/rack/handler/webrick.rb:95:in `service'
/app/vendor/ruby-2.7.5/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
/app/vendor/ruby-2.7.5/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
/app/vendor/ruby-2.7.5/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'
```

**Comment by zoeself** [comment]
@0pdd thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-08-03T13:49:23.949877``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).
